import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { signIn, signOut } from "next-auth/react";
import Button from "shared";
import { api, type RouterOutputs } from "~/utils/api";

const EventCard: React.FC<{
  event: RouterOutputs["event"]["all"][number];
  onEventDelete?: () => void;
}> = ({ event, onEventDelete: onPostDelete }) => {
  return (
    <div className="flex w-full max-w-2xl flex-row rounded-lg bg-white/10 p-4 transition-all hover:scale-[101%]">
      <div className="flex-grow">
        <h2 className="text-2xl font-bold text-[hsl(280,100%,70%)]">
          {event.title || <i>Untitled</i>}
        </h2>
        <p className="mt-2 text-sm">{event.description || <i>No content</i>}</p>
      </div>
      <div>
        <span
          className="cursor-pointer text-sm font-bold uppercase text-pink-400"
          onClick={onPostDelete}
        >
          Delete
        </span>
      </div>
    </div>
  );
};

const CreatePostForm: React.FC = () => {
  const utils = api.useContext();

  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");

  const { mutate } = api.event.create.useMutation({
    async onSuccess() {
      setTitle("");
      setDescription("");
      await utils.event.all.invalidate();
    },
  });

  return (
    <div className="flex w-[80vw] flex-col p-4 md:w-[60vw] xl:w-[35vw]">
      <input
        className="mb-2 rounded bg-white/10 p-2 text-white"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        placeholder="Title"
      />
      <input
        className="mb-2 rounded bg-white/10 p-2 text-white"
        value={description}
        onChange={(e) => setDescription(e.target.value)}
        placeholder="Description"
      />
      <button
        className="rounded bg-pink-700 p-2 font-bold"
        onClick={() => {
          mutate({
            title,
            description,
            visibility: "ATTENDEES",
          });
        }}
      >
        Create
      </button>
    </div>
  );
};

const Home: NextPage = () => {
  const eventQuery = api.event.all.useQuery();

  const deleteEventMutation = api.event.delete.useMutation({
    onSettled: () => eventQuery.refetch(),
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <div className="container mt-12 flex flex-col items-center justify-center gap-4 px-4 py-8">
          <AuthShowcase />

          <CreatePostForm />

          {eventQuery.data ? (
            <div>
              {eventQuery.data?.length === 0 ? (
                <span>There are no events!</span>
              ) : (
                <div className="flex h-[40vh] w-[80vw] justify-center overflow-y-scroll px-4 text-2xl md:w-[60vw] xl:w-[35vw]">
                  <div className="flex w-full flex-col gap-4">
                    {eventQuery.data?.map((p) => {
                      return (
                        <EventCard
                          key={p.id}
                          event={p}
                          onEventDelete={() => deleteEventMutation.mutate(p.id)}
                        />
                      );
                    })}
                  </div>
                </div>
              )}
            </div>
          ) : (
            <p>Loading..</p>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: session } = api.auth.getSession.useQuery();

  const { data: secretMessage } = api.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: !!session?.user },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      {session?.user && (
        <p className="text-center text-2xl text-white">
          {session && <span>Logged in as {session?.user?.name}</span>}
          {secretMessage && <span> - {secretMessage}</span>}
        </p>
      )}
      <Button
        // className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={session ? () => void signOut() : () => void signIn()}
        variant="primary"
      >
        {session ? "Sign out" : "Sign in"}
      </Button>
    </div>
  );
};
