name: on-merge-main
on:
  push:
    branches:
      - "main"

jobs:
  deploy-migration:
    name: Deploy migration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
          cache: "yarn"
      - run: yarn
      - name: Run production migration
        run: yarn run db:deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_PROD }}
  create-release:
    name: create release action
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: {{release-${{ steps.date.outputs.date }}}}
          files: |
            *
